name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_REGISTRY: "ghcr.io"
  REGISTRY_USER: "${{ github.repository_owner }}"
  REGISTRY_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  IMAGE_REPO: "ghcr.io/${{ github.repository_owner }}"
  IMAGE_NAME: "ml-workspace_custom"

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Login docker 
      run: |
        echo ${{ env.REGISTRY_TOKEN }} | docker login ${{ env.IMAGE_REGISTRY }} -u ${{ env.REGISTRY_USER }} --password-stdin

    - name: Docker build
      run: |
        docker build . --file Dockerfile --tag ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:latest

    - name: Push docker image
      run: |
        docker push ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:latest